import crypto from 'node:crypto';

const REPO=process.env.GITHUB_REPOSITORY||'avec-franquias/Dashboard-comercial-avec';
const BRANCH=process.env.GITHUB_BRANCH||'main';
function cors(req,res){const o=req.headers.origin||'*';res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,PUT,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Cache-Control','no-store')}
function auth(req){const secret=process.env.GITHUB_TOKEN||process.env.PORTAL_SESSION_SECRET;if(!secret)throw Object.assign(new Error('Chave de sessao indisponivel'),{status:500});const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const [p,s]=token.split('.');if(!p||!s)throw Object.assign(new Error('Entre novamente'),{status:401});const exp=crypto.createHmac('sha256',secret).update(p).digest('base64url');const a=Buffer.from(s),b=Buffer.from(exp);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw Object.assign(new Error('Sessao invalida'),{status:401});const d=JSON.parse(Buffer.from(p,'base64url').toString('utf8'));if(Date.now()>Number(d.exp||0))throw Object.assign(new Error('Sessao expirada'),{status:401});if(!d.franquiaId&&d.papel!=='admin')throw Object.assign(new Error('Usuario ainda nao vinculado a uma franquia'),{status:403});return d}
async function gh(path,opts={}){const t=process.env.GITHUB_TOKEN;if(!t)throw Object.assign(new Error('Armazenamento indisponivel'),{status:500});const r=await fetch('https://api.github.com/repos/'+REPO+path,{...opts,headers:{Authorization:'Bearer '+t,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json','User-Agent':'avec-portal-api'}});const x=await r.text();let j={};try{j=x?JSON.parse(x):{}}catch{};if(!r.ok&&r.status!==404)throw Object.assign(new Error(j.message||'Falha no armazenamento'),{status:r.status});return {status:r.status,j}}
function safe(s){return String(s||'').toLowerCase().replace(/[^a-z0-9_-]/g,'-').slice(0,80)}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();try{const u=auth(req);const franquia=safe(u.franquiaId||('admin-'+u.login));const modulo=safe(req.query?.modulo||req.body?.modulo||'geral');const file='franquias/'+franquia+'/'+modulo+'.json';const cur=await gh('/contents/'+file+'?ref='+encodeURIComponent(BRANCH));if(req.method==='GET'){if(cur.status===404)return res.status(200).json({ok:true,franquiaId:franquia,modulo,dados:null});return res.status(200).json({ok:true,franquiaId:franquia,modulo,dados:JSON.parse(Buffer.from(cur.j.content,'base64').toString('utf8'))})}if(!['PUT','POST'].includes(req.method))return res.status(405).json({ok:false,error:'Metodo nao permitido'});const dados=req.body?.dados??req.body;const doc={franquiaId:franquia,modulo,atualizadoEm:new Date().toISOString(),atualizadoPor:u.login,dados};const body={message:'Portal: salva '+modulo+' da franquia '+franquia,content:Buffer.from(JSON.stringify(doc,null,2)).toString('base64'),branch:BRANCH};if(cur.status===200)body.sha=cur.j.sha;const out=await gh('/contents/'+file,{method:'PUT',body:JSON.stringify(body)});return res.status(200).json({ok:true,franquiaId:franquia,modulo,commit:out.j.commit?.sha})}catch(e){return res.status(e.status||500).json({ok:false,error:e.message})}}
